/**
 * Signal tool — reads daily signal files produced by the external
 * signal-pipeline project.
 *
 * Schema mirrors signal-pipeline's schemas/signal.py SignalReport.
 * Pydantic's Optional[...] fields serialize as explicit JSON null,
 * so we use .nullable().optional() to accept both shapes.
 */

import { tool, type Tool } from 'ai'
import { z } from 'zod'
import { readFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { join, resolve } from 'node:path'

// ==================== Schemas (mirror signal-pipeline/schemas/signal.py) ====================

const actionHintSchema = z.enum(['BUY', 'SELL', 'HOLD', 'CLOSE'])
const triggerSchema = z.enum(['golden_cross', 'death_cross', 'qlib_top_rank', 'qlib_bottom_rank', 'none'])
const convictionSchema = z.enum(['low', 'medium', 'high'])

const generatorMetaSchema = z.object({
  name: z.string(),
  version: z.string(),
  params: z.record(z.string(), z.union([z.string(), z.number()])).default({}),
  trained_on: z.string().nullable().optional(),
  ic: z.number().nullable().optional(),
  rank_ic: z.number().nullable().optional(),
})

const signalEntrySchema = z.object({
  symbol: z.string(),
  action_hint: actionHintSchema,
  trigger: triggerSchema,
  conviction: convictionSchema.default('medium'),
  score: z.number().nullable().optional(),
  rank: z.number().int().nullable().optional(),
  tier: z.union([z.literal(1), z.literal(2)]).nullable().optional(),
  short_ma: z.number().nullable().optional(),
  long_ma: z.number().nullable().optional(),
  close: z.number().nullable().optional(),
  date_of_signal: z.string().nullable().optional(),
  reasoning: z.string().nullable().optional(),
})

const portfolioSuggestionSchema = z.object({
  mode: z.enum(['equal_weight_top_N', 'react_to_crossover', 'manual']),
  top_n: z.number().int().nullable().optional(),
  position_size_per_signal_usd: z.number().nullable().optional(),
  max_position_pct: z.number().default(15.0),
  rebalance: z.string().nullable().optional(),
})

export const signalReportSchema = z.object({
  date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'date must be YYYY-MM-DD'),
  generator: generatorMetaSchema,
  universe: z.array(z.string()).min(1),
  signals: z.array(signalEntrySchema),
  no_signal: z.array(z.string()).default([]),
  insufficient_data: z.array(z.string()).default([]),
  stale_data: z.array(z.string()).default([]),
  portfolio_suggestion: portfolioSuggestionSchema,
  generated_at: z.string(),
})

export type SignalReport = z.infer<typeof signalReportSchema>

// ==================== Helpers ====================

/** Expand leading ~/ to homedir. fs.readFile does not do this natively. */
export function expandHome(p: string): string {
  if (p.startsWith('~/') || p === '~') {
    return p === '~' ? homedir() : join(homedir(), p.slice(2))
  }
  return p
}

/** Today's date in UTC as YYYY-MM-DD. */
function todayUtcYmd(): string {
  return new Date().toISOString().slice(0, 10)
}

// ==================== Factory ====================

export function createSignalTools(signalDir: string): Record<string, Tool> {
  const baseDir = resolve(expandHome(signalDir))

  return {
    readSignal: tool({
      description: `Read the daily signal file generated by the external signal-pipeline project.
These signals are HINTS, not commands — they indicate suggested BUY/SELL entries based on strategies like MA crossover (Phase 1) or ML factor ranking (Phase 2).
Signals apply to the whole configured universe, not any specific account.

To use a signal, first call listAccounts and getPortfolio to know what you can trade, then intersect the signal.universe with each account's whitelist. Only stage orders for symbols that are in all three sets (signal, whitelist, Adrian's capital available).

insufficient_data contains symbols where the generator did not have enough bars to evaluate (e.g. recently-listed tickers). stale_data contains symbols whose latest bar is older than 5 business days. The generator rejected them as too stale to evaluate. Treat these as data quality issues — they should NOT be considered for staging. If a symbol you expected to trade appears in stale_data, investigate the data source before manually overriding.

The tool returns the full SignalReport plus a compact summary. If no signal file exists for the date, it returns {found: false, error: ...} so you know there is nothing to act on.`,
      inputSchema: z.object({
        date: z.string()
          .regex(/^\d{4}-\d{2}-\d{2}$/, 'date must be YYYY-MM-DD')
          .optional()
          .describe('Target signal date YYYY-MM-DD. Defaults to today (UTC).'),
      }),
      execute: async ({ date }) => {
        const targetDate = date ?? todayUtcYmd()
        const signalPath = join(baseDir, `${targetDate}.json`)
        let raw: string
        try {
          raw = await readFile(signalPath, 'utf-8')
        } catch (err: unknown) {
          if (err instanceof Error && 'code' in err && (err as NodeJS.ErrnoException).code === 'ENOENT') {
            return {
              found: false,
              path: signalPath,
              error: `No signal file for ${targetDate}. The signal-pipeline may not have run yet for this date — try a different --date, or run the generator in the signal-pipeline project first.`,
            }
          }
          throw err
        }

        let parsed: unknown
        try {
          parsed = JSON.parse(raw)
        } catch (err) {
          return {
            found: true,
            path: signalPath,
            error: `Signal file exists but contains invalid JSON: ${err instanceof Error ? err.message : String(err)}`,
          }
        }

        const validation = signalReportSchema.safeParse(parsed)
        if (!validation.success) {
          return {
            found: true,
            path: signalPath,
            error: `Signal file failed schema validation. The signal-pipeline may have emitted a malformed payload. Details: ${validation.error.message}`,
          }
        }

        const signal = validation.data
        const buyCount = signal.signals.filter((s) => s.action_hint === 'BUY').length
        const sellCount = signal.signals.filter((s) => s.action_hint === 'SELL').length

        return {
          found: true,
          path: signalPath,
          signal,
          summary: {
            date: signal.date,
            generator: `${signal.generator.name}@${signal.generator.version}`,
            universe_size: signal.universe.length,
            signals_count: signal.signals.length,
            buy_count: buyCount,
            sell_count: sellCount,
            no_signal_count: signal.no_signal.length,
            insufficient_data_count: signal.insufficient_data.length,
            stale_data_count: signal.stale_data.length,
            stale_tickers: signal.stale_data,
            top_signals: signal.signals.slice(0, 5).map((s) => ({
              symbol: s.symbol,
              action: s.action_hint,
              tier: s.tier ?? null,
              trigger: s.trigger,
              conviction: s.conviction,
              close: s.close ?? null,
            })),
          },
        }
      },
    }),
  }
}
